site_name: Google Test Docs Mirror
nav:
    - Home: index.md
    - Google Test:
        - Index: gtest/googletest/docs/index.md
        - Primer: gtest/googletest/docs/primer.md
        - FAQ: gtest/googletest/docs/faq.md
        - Advanced: gtest/googletest/docs/advanced.md
        - pkg-config: gtest/googletest/docs/pkgconfig.md
        - Samples: gtest/googletest/docs/samples.md
    - Google Mock:
        - Index: gtest/googlemock/docs/index.md
        - For Dummies: gtest/googlemock/docs/for_dummies.md
        - Cheat Sheet: gtest/googlemock/docs/cheat_sheet.md
        - Cookbook: gtest/googlemock/docs/cook_book.md
        - FAQ: gtest/googlemock/docs/gmock_faq.md
        - Pump Manual: gtest/googlemock/docs/pump_manual.md
        - Community Created Documentation: gtest/googlemock/docs/community_created_documentation.md
            - ElectricRCAircraftGuy \- insights: community_created_documentation/insights.md
repo_url: https://github.com/google/googletest
repo_name: Google Test
# edit_uri: "blob/master/googletest/docs/"
edit_uri: ""
theme:
    name: 'material'
markdown_extensions:
    - toc:
        permalink: True
